### ISSUE TITLE
[feat] 캐릭터 무기별 애니메이터 연동으로 분리하기

### ISSUE THREAD

**Issue by RudinP** [CardBattle/Beta#1]
### 문제 상황
- 캐릭터 프리팹에서 무기가 달라져도, 소드 기준으로 애니메이터가 있는 상황

<hr>

### 해결 방안
- 캐릭터 무기 스프라이트만 모아둔 파일을 따로 생성, 캐릭터의 WeaponType에 따라 애니메이터를 별도로 연결해주도록 수정한다.

<hr>

### TODO
- [x] 캐릭터 무기 그리기(활, 마법봉)
- [x] WeaponType에 따른 애니메이터 연동
- [x] WeaponType별 애니메이터 수정
