### ISSUE TITLE
[feat]BattleManager 보완 및 플레이어 덱 리스트 확인 추가 

### ISSUE THREAD

**Issue by ProPim** [CardBattle/Beta#20]
### 문제 상황
- 플레이어 덱 리스트 확인 구현이 가능한지 확인(가능할거 같으면 추가)
- 전투시스템 부분 좀 더 꼼꼼하게 수정 및 구현 추가

<hr>

### 해결 방안
- 플레이어 덱 리스트 확인 구현이 가능한지 확인(가능할거 같으면 추가)
- BattleManager 부분 코드들 수정 및 지금 없는 전투 시스템 구현 추가
- UIManager 부분 코드들 추가 및 수정

### TODO
- [x] 플레이어 덱 리스트 확인 구현이 가능한지 확인(가능할거 같으면 추가)
- [x] UIManager 부분 코드들 추가 및 수정
- [x] BattleManager 부분 코드들 수정 및 지금 없는 전투 시스템 구현 추가
