### ISSUE TITLE
[feat]튜토리얼 다시보기 버튼, 전투씬 보완, 튜토리얼 이미지 소스 추가

### ISSUE THREAD

**Issue by ProPim** [CardBattle/Beta#31]
### 문제 상황
- 튜토리얼 다시보기 버튼 부재 
- 전투씬 남은덱 수 텍스트 부재
- 튜토리얼 이미지 소스 한개 부재

<hr>

### 해결 방안
- 튜토리얼 다시보기 버튼 추가
- 전투씬 남은덱 수 텍스트 추가
- 튜토리얼 이미지 소스 추가

<hr>

### TODO
- [x] 튜토리얼 다시보기 버튼 추가
- [x] 전투씬 남은덱 수 텍스트 추가
- [x] 튜토리얼 이미지 소스 추가
