### ISSUE TITLE
[feat]Magic 카드 구현

### ISSUE THREAD

**Issue by zjaxjrhkd** [CardBattle/Beta#37]
### 문제 상황
- Magic 카드의 부재
<hr>

### 해결 방안
- fire, ice, electric 계열 구현

<hr>

### TODO
- [ ] 1. fire 계열 구현
- [ ] 2. ice 계열 구현
- [ ] 3. electric  계열 구현
